CREATE TABLE IF NOT EXISTS notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    recommendation_id BIGINT,
    category VARCHAR(100),
    message TEXT NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    event_created_at TIMESTAMP,
    sent_at TIMESTAMP NOT NULL
);
