CREATE TABLE IF NOT EXISTS recommendations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_content_id BIGINT NOT NULL,
    source_content_title VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    message TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL
);
